### ISSUE TITLE
剪枝报错

### ISSUE THREAD

**Issue by MAMAYUH** [midasklr/yolov5prune#12]
C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\init.py:388: UserWarning: Initializing zero-element tensors is a no-op
  warnings.warn("Initializing zero-element tensors is a no-op")
Traceback (most recent call last):
  File "prune.py", line 809, in <module>
    test_prune(opt.data,
  File "prune.py", line 470, in test_prune
    pruned_model = ModelPruned(maskbndict=maskbndict, cfg=pruned_yaml, ch=3).cuda()
  File "C:\Users\Administrator\Desktop\yolov5prune-main\models\yolo.py", line 250, in __init__
    self.model, self.save, self.from_to_map = parse_pruned_model(self.maskbndict, deepcopy(self.yaml), ch=[ch])  # model, savelist
  File "C:\Users\Administrator\Desktop\yolov5prune-main\models\yolo.py", line 717, in parse_pruned_model
    m_ = nn.Sequential(*[m(*args) for _ in range(n)]) if n > 1 else m(*args)  # module
  File "C:\Users\Administrator\Desktop\yolov5prune-main\models\common.py", line 131, in __init__
    self.cv3 = Conv(2 * c_, c2, 1)  # act=FReLU(c2)
  File "C:\Users\Administrator\Desktop\yolov5prune-main\models\common.py", line 35, in __init__
    self.conv = nn.Conv2d(c1, c2, k, s, autopad(k, p), groups=g, bias=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 430, in __init__
    super(Conv2d, self).__init__(
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 131, in __init__
    self.weight = Parameter(torch.empty(
TypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 
 prune.py加载剪枝后的模型报错，怎么看也不会是conv代码的问题吧，之前训练都好好的.....求教

**Comment by LMH0411** [comment]
请问解决了吗

**Comment by QuanShengNB** [comment]
请问解决了吗
