### ISSUE TITLE
在进行稀疏化的时候遇到报错

### ISSUE THREAD

**Issue by chbw818** [midasklr/yolov5prune#123]
大佬您好，我在运行train_sparsity.py 的时候出现了报错：
`RuntimeError: Given groups=1, weight of size [512, 1024, 1, 1], expected input[1, 512, 8, 8] to have 1024 channels, but got 512 channels instead`
请问应该如何解决呢，谢谢！

**Comment by chbw818** [comment]
`Traceback (most recent call last):
  File "train_sparsity.py", line 598, in <module>
    train(hyp, opt, device, tb_writer)
  File "train_sparsity.py", line 94, in train
    model = Model(opt.cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/root/autodl-tmp/yolov5prune/models/yolo.py", line 103, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in self.forward(torch.zeros(1, ch, s, s))])  # forward
  File "/root/autodl-tmp/yolov5prune/models/yolo.py", line 119, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/root/autodl-tmp/yolov5prune/models/yolo.py", line 150, in forward_once
    x = m(x)  # run
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/autodl-tmp/yolov5prune/models/common.py", line 157, in forward
    x = self.cv1(x)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/autodl-tmp/yolov5prune/models/common.py", line 42, in forward
    return self.act(self.bn(self.conv(x)))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [512, 1024, 1, 1], expected input[1, 512, 8, 8] to have 1024 channels, but got 512 channels instead`

**Comment by fangxuehouwuming** [comment]
同问

**Comment by chuang-sir** [comment]
应该是图片分辨率问题
