### ISSUE TITLE
prune.py脚本运行报错 too many indices for tensor demension 3

### ISSUE THREAD

**Issue by bigFatCatTom** [midasklr/yolov5prune#127]
Traceback (most recent call last):
  File "prune.py", line 816, in <module>
    opt=opt
  File "prune.py", line 500, in test_prune
    pruned_layer.weight.data = w[:,formerin, :, :].clone()
IndexError: too many indices for tensor of dimension 3

**Comment by bigFatCatTom** [comment]
https://github.com/midasklr/yolov5prune/issues/36#issuecomment-918724794 this issue has solved my issue.
