### ISSUE TITLE
v7.0版本能用吗？

### ISSUE THREAD

**Issue by Doris-miao** [midasklr/yolov5prune#134]
我用的是v5的7.0版本,稀疏训练的时候会报错，求解答
报错如下：Traceback (most recent call last):   File "C:\Users\Admin\Desktop\jianzhi\yolov5prune-6.0\train_sparity.py", line 674, in <module>     main(opt)   File "C:\Users\Admin\Desktop\jianzhi\yolov5prune-6.0\train_sparity.py", line 571, in main     train(opt.hyp, opt, device, callbacks)   File "C:\Users\Admin\Desktop\jianzhi\yolov5prune-6.0\train_sparity.py", line 117, in train     ckpt = torch.load(weights, map_location=device)  # load checkpoint   File "C:\Users\Admin\.conda\envs\yolov5-7.0\lib\site-packages\torch\serialization.py", line 607, in load     return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)   File "C:\Users\Admin\.conda\envs\yolov5-7.0\lib\site-packages\torch\serialization.py", line 882, in _load     result = unpickler.load()   File "C:\Users\Admin\.conda\envs\yolov5-7.0\lib\site-packages\torch\serialization.py", line 875, in find_class     return super().find_class(mod_name, name) AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo' from 'C:\\Users\\Admin\\Desktop\\jianzhi\\yolov5prune-6.0\\models\\yolo.py'>

**Comment by peiki99** [comment]
不能，要自己移植改一下捏

**Comment by pppppsb** [comment]
> 不能，要自己移植改一下捏
请问怎么移植，你有源代码吗？我现在需要实现v5 7.0版本的剪枝操作。

**Comment by Polaris-F** [comment]
> > 不能，要自己移植改一下捏
> > 请问怎么移植，你有源代码吗？我现在需要实现v5 7.0版本的剪枝操作。

在稀疏训练的时候可以直接把那一小块 加到 backward那里
然后
参数里面要剪枝的部分剪掉 
用新的参数结构训练就行了 
在v8上实测有效

**Comment by wusaisa** [comment]
> 在v8上实测有效

你好，可以求指教怎么在yolov8上进行剪枝吗？有偿~谢谢~

**Comment by 223330795** [comment]
> > > 不能，要自己移植改一下捏
> > > 请问怎么移植，你有源代码吗？我现在需要实现v5 7.0版本的剪枝操作。
> 
> 在稀疏训练的时候，可以直接把那一小块 加到 backward， 那里 然后 参数里面要剪枝的部分剪掉 用新的参数结构训练就行了 在 v8上实测有效

您好，请问下具体怎么改，我用7.0进行稀疏化map反而升高了，我现在在找问题
