### ISSUE TITLE
train_sparsity.py运行错误

### ISSUE THREAD

**Issue by kangbeen** [midasklr/yolov5prune#14]
Traceback (most recent call last):
  File "/home/k/yolov5_prune/train_sparsity.py", line 601, in <module>
    train(hyp, opt, device, tb_writer)
  File "/home/k/yolov5_prune/train_sparsity.py", line 340, in train
    optimizer.step()
  File "/home/k/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/k/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/optim/optimizer.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/home/k/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/k/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/optim/adamw.py", line 98, in step
    exp_avgs.append(state['exp_avg'])
KeyError: 'exp_avg'

**Comment by kangbeen** [comment]
请问一下，这个错误怎么解决？自己的数据集训练的模型。

**Comment by kangbeen** [comment]
已解决

**Comment by lrh454830526** [comment]
> 

你好 请问你怎么解决的这个问题
