### ISSUE TITLE
剪枝失败

### ISSUE THREAD

**Issue by sonica1987** [midasklr/yolov5prune#15]
步骤按照readme.md进行操作：1、正常训练 （yolov5s 模型 57M） 2、稀疏训练（模型14.4M）
执行剪枝：
prune.py 378行： percent_limit = (sorted_bn == highest_thre).nonzero()[0, 0].item() / len(bn_weights)  报错，改为：
percent_limit = (sorted_bn == highest_thre).nonzero(as_tuple=False)[0, 0].item() / len(bn_weights)后继续运行剪枝报错如下：

model.0.conv.bn BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.1.bn BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.2.cv1.bn BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.2.cv2.bn BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.2.cv3.bn BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.3.bn BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.4.cv1.bn BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.4.cv2.bn BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.4.cv3.bn BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.5.bn BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.6.cv1.bn BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.6.cv2.bn BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.6.cv3.bn BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.7.bn BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.8.cv1.bn BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.8.cv2.bn BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.9.cv1.bn BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.9.cv2.bn BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.9.cv3.bn BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.9.m.0.cv1.bn BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.9.m.0.cv2.bn BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.10.bn BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.13.cv1.bn BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.13.cv2.bn BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.13.cv3.bn BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.13.m.0.cv1.bn BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.13.m.0.cv2.bn BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.14.bn BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.17.cv1.bn BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.17.cv2.bn BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.17.cv3.bn BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.17.m.0.cv1.bn BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.17.m.0.cv2.bn BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.18.bn BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.20.cv1.bn BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.20.cv2.bn BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.20.cv3.bn BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.20.m.0.cv1.bn BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.20.m.0.cv2.bn BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.21.bn BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.23.cv1.bn BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.23.cv2.bn BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.23.cv3.bn BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.23.m.0.cv1.bn BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
model.23.m.0.cv2.bn BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
0.095703125
Suggested Gamma threshold should be less than 0.6982.
The corresponding prune ratio is 0.096, but you can set higher.

Traceback (most recent call last):
File "/home/keroro/Downloads/yolov5prune-main/prune.py", line 808, in <module>
opt=opt
File "/home/keroro/Downloads/yolov5prune-main/prune.py", line 383, in test_prune
assert opt.percent < percent_limit, f"Prune ratio should less than {percent_limit}, otherwise it may cause error!!!"
AssertionError: Prune ratio should less than 0.095703125, otherwise it may cause error!!!

**Comment by sonica1987** [comment]
问题解决了，是模型剪枝模型路径没设对
