### ISSUE TITLE
train.py报错

### ISSUE THREAD

**Issue by gjr2019** [midasklr/yolov5prune#24]
作者您好，当我按您的步骤运行train.py的时候出现如下报错：
Traceback (most recent call last):
  File "train.py", line 548, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 193, in train
    image_weights=opt.image_weights, quad=opt.quad, prefix=colorstr('train: '))
  File "/project/train/src_repo/utils/datasets.py", line 72, in create_dataloader
    prefix=prefix)
  File "/project/train/src_repo/utils/datasets.py", line 385, in __init__
    cache, exists = torch.load(cache_path), True  # load
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: STACK_GLOBAL requires str
请问这如何解决呢？

**Comment by yumeng88** [comment]
请问您解决了吗？可以分享一下吗
