### ISSUE TITLE
_pickle.UnpicklingError: STACK_GLOBAL requires str

### ISSUE THREAD

**Issue by yumeng88** [midasklr/yolov5prune#33]
![image](https://user-images.githubusercontent.com/56550062/131600819-a435a4c9-e59a-4f2e-94f0-9ef02206df25.png)
作者您好，当我按您的步骤运行train.py或者train_sparsity.py的时候出现如下报错：
Traceback (most recent call last):
File "train.py", line 548, in
train(hyp, opt, device, tb_writer)
File "train.py", line 193, in train
image_weights=opt.image_weights, quad=opt.quad, prefix=colorstr('train: '))
File "/project/train/src_repo/utils/datasets.py", line 72, in create_dataloader
prefix=prefix)
File "/project/train/src_repo/utils/datasets.py", line 385, in init
cache, exists = torch.load(cache_path), True # load
File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 608, in load
return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 777, in _legacy_load
magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: STACK_GLOBAL requires str
请问这如何解决呢？

之前也有同学出现这个问题想问一下是怎么解决的

**Comment by HandsLing** [comment]
把你原来训练时候的那个cache文件找出来，删掉，再次训练的时候会重新生成一个，以后再在这个代码下面跑就不会报错了

**Comment by yumeng88** [comment]
@HandsLing 好的多谢
