### ISSUE TITLE
6.0时报错utils

### ISSUE THREAD

**Issue by suhanling** [midasklr/yolov5prune#72]
ModuleNotFoundError: No module named 'utils.loggers.wandb' 请问这是哪里报错 怎么解决

**Comment by soujie** [comment]
其他分支下复制过去就行了

**Comment by msddmzy** [comment]
> 其他分支下复制过去就行了

师兄，原始的train.py是可以正常训练的，在进行稀疏训练的时候，出现了上面这个问题（ModuleNotFoundError: No module named 'utils.loggers.wandb' ），我看到您的回复后，从Ｕ神的YOLOv5 6.0版本的utils文件夹下直接把loggers文件给复制过去了，然后在执行稀疏训练，程序可以训练一个epoch，然后就报错了，内容如下：
Epoch   gpu_mem       box       obj       cls    labels  img_size
      0/99     1.05G   0.05454  0.006302  0.007673        10       512: 100%|██████████| 18/18 [00:07<00:00,  2.39it/s]                                              
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 10/10 [00:01<00:00,  7.32it/s]                              
                 all         80        301    0.00979     0.0183    0.00191   0.000324
Traceback (most recent call last):
  File "train_sparity.py", line 678, in <module>
    main(opt)
  File "train_sparity.py", line 575, in main
    train(opt.hyp, opt, device, callbacks)
  File "train_sparity.py", line 423, in train
    callbacks.run('on_fit_epoch_end', log_vals, bn_weights.numpy() ,epoch, best_fitness, fi)
  File "/home/msdd/anaconda3/envs/pytov5/yolov5prune-6.0/utils/callbacks.py", line 77, in run
    logger['callback'](*args, **kwargs)
TypeError: on_fit_epoch_end() takes 5 positional arguments but 6 were given
师兄，您知道这个是什么问题吗？

**Comment by msddmzy** [comment]
> ModuleNotFoundError: No module named 'utils.loggers.wandb' 请问这是哪里报错 怎么解决

师兄，您这个问题解决了吗？
我也出现了上面这个问题（ModuleNotFoundError: No module named 'utils.loggers.wandb' ），然后我从Ｕ神的YOLOv5 6.0版本的utils文件夹下直接把loggers文件给复制过去了，原始的train.py是可以正常训练的，然后在执行稀疏训练，程序可以训练一个epoch，然后就报错了，内容如下：
Epoch gpu_mem box obj cls labels img_size
0/99 1.05G 0.05454 0.006302 0.007673 10 512: 100%|██████████| 18/18 [00:07<00:00, 2.39it/s]
Class Images Labels P R mAP@.5 mAP@.5:.95: 100%|██████████| 10/10 [00:01<00:00, 7.32it/s]
all 80 301 0.00979 0.0183 0.00191 0.000324
Traceback (most recent call last):
File "train_sparity.py", line 678, in
main(opt)
File "train_sparity.py", line 575, in main
train(opt.hyp, opt, device, callbacks)
File "train_sparity.py", line 423, in train
callbacks.run('on_fit_epoch_end', log_vals, bn_weights.numpy() ,epoch, best_fitness, fi)
File "/home/msdd/anaconda3/envs/pytov5/yolov5prune-6.0/utils/callbacks.py", line 77, in run
logger['callback'](*args, **kwargs)
TypeError: on_fit_epoch_end() takes 5 positional arguments but 6 were given
师兄，您知道这个是什么问题吗？
