### ISSUE TITLE
剪枝时报错：KeyError: 'model.0.conv.bn'

### ISSUE THREAD

**Issue by weinanyu** [midasklr/yolov5prune#74]
试了很多的稀疏度和剪枝率都报这个同样的错，不知如何解决

**Comment by weinanyu** [comment]
还有KeyError: 'model.4.m.2.cv1.bn'

**Comment by msddmzy** [comment]
> 试了很多的稀疏度和剪枝率都报这个同样的错，不知如何解决

师兄，您是使用6.0版本训练的吗？

**Comment by weinanyu** [comment]
是的 请问是因为使用6.0版本才出现的问题吗？


------------------ 原始邮件 ------------------
发件人: msddmzy ***@***.***&gt;
发送时间: 2022年3月5日 21:56
收件人: midasklr/yolov5prune ***@***.***&gt;
抄送: weinanyu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [midasklr/yolov5prune] 剪枝时报错：KeyError: 'model.0.conv.bn' (Issue #74)





  
试了很多的稀疏度和剪枝率都报这个同样的错，不知如何解决
  
师兄，您是使用6.0版本训练的吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weinanyu** [comment]
好像也不是用的6.0，可能是因为我改动过SPP？


------------------ 原始邮件 ------------------
发件人: msddmzy ***@***.***&gt;
发送时间: 2022年3月5日 21:56
收件人: midasklr/yolov5prune ***@***.***&gt;
抄送: weinanyu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [midasklr/yolov5prune] 剪枝时报错：KeyError: 'model.0.conv.bn' (Issue #74)





  
试了很多的稀疏度和剪枝率都报这个同样的错，不知如何解决
  
师兄，您是使用6.0版本训练的吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by msddmzy** [comment]
> 是的 请问是因为使用6.0版本才出现的问题吗？
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: msddmzy ***@***.***&gt; 发送时间: 2022年3月5日 21:56 收件人: midasklr/yolov5prune ***@***.***&gt; 抄送: weinanyu ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [midasklr/yolov5prune] 剪枝时报错：KeyError: 'model.0.conv.bn' (Issue #74) 试了很多的稀疏度和剪枝率都报这个同样的错，不知如何解决 师兄，您是使用6.0版本训练的吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

应该不是因为6.0版本出的问题吧

**Comment by msddmzy** [comment]
> 是的 请问是因为使用6.0版本才出现的问题吗？
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: msddmzy ***@***.***&gt; 发送时间: 2022年3月5日 21:56 收件人: midasklr/yolov5prune ***@***.***&gt; 抄送: weinanyu ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [midasklr/yolov5prune] 剪枝时报错：KeyError: 'model.0.conv.bn' (Issue #74) 试了很多的稀疏度和剪枝率都报这个同样的错，不知如何解决 师兄，您是使用6.0版本训练的吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

师兄，您在执行稀疏训练的时候没有报错啥的吧，
up主上传的6.0版本的代码好像缺少/utils/loggers/里面的文件，我从Ｕ神的YOLOv5 6.0版本的utils文件夹下直接把loggers文件给复制过去了，正常训练没有问题，但执行稀疏训练的时候遇到一个问题：
Starting training for 100 epochs...

     Epoch   gpu_mem       box       obj       cls    labels  img_size
      0/99     1.05G   0.05454  0.006302  0.007673        10       512: 100%|██████████| 18/18 [00:07<00:00,  2.39it/s]                                              
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 10/10 [00:01<00:00,  7.32it/s]                              
                 all         80        301    0.00979     0.0183    0.00191   0.000324
Traceback (most recent call last):
  File "train_sparity.py", line 678, in <module>
    main(opt)
  File "train_sparity.py", line 575, in main
    train(opt.hyp, opt, device, callbacks)
  File "train_sparity.py", line 423, in train
    callbacks.run('on_fit_epoch_end', log_vals, bn_weights.numpy() ,epoch, best_fitness, fi)
  File "/home/msdd/anaconda3/envs/pytov5/yolov5prune-6.0/utils/callbacks.py", line 77, in run
    logger['callback'](*args, **kwargs)
TypeError: on_fit_epoch_end() takes 5 positional arguments but 6 were given
您有遇到过这种问题吗？帮我看一下吧

**Comment by weinanyu** [comment]
不好意思我给您说错了，我用的是5.0版本，但是自己改动过SPP（因为之前训练的时候用up的代码这一部分有报错）。在稀疏训练过程中没有出现过报错。
对于您这个报错的话，您可以看看报错的这个函数引用的参数个数或是参数写法是不是有问题（从字面意思来看）？

**Comment by yezechen** [comment]
> 好像也不是用的6.0，可能是因为我改动过SPP？
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: msddmzy ***@***.***&gt; 发送时间: 2022年3月5日 21:56 收件人: midasklr/yolov5prune ***@***.***&gt; 抄送: weinanyu ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [midasklr/yolov5prune] 剪枝时报错：KeyError: 'model.0.conv.bn' (Issue #74) 试了很多的稀疏度和剪枝率都报这个同样的错，不知如何解决 师兄，您是使用6.0版本训练的吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

请问您解决了吗

**Comment by weinanyu** [comment]
> 

还没有

**Comment by syf0518** [comment]
> > 
> 
> 还没有

请问您现在解决了吗？我用6.0版本训练也报这个错。
