### ISSUE TITLE
6.0版本解决（ModuleNotFoundError: No module named 'utils.loggers.wandb' ）

### ISSUE THREAD

**Issue by msddmzy** [midasklr/yolov5prune#75]
其他分支下复制过去就行了

_Originally posted by @soujie in https://github.com/midasklr/yolov5prune/issues/72#issuecomment-1054951892_

师兄，原始的train.py是可以正常训练的，在进行稀疏训练的时候，出现了上面这个问题（ModuleNotFoundError: No module named 'utils.loggers.wandb' ），
我看到您的回复后，从Ｕ神的YOLOv5 6.0版本的utils文件夹下直接把loggers文件给复制过去了，记得只要wandb文件就好了，其他的文件不要动

**Comment by leeformoney** [comment]
on_fit_epoch_end() missing 1 required positional argument: 'fi'
复制过去正常训练显示的是这个，但是可以进行稀疏训练，请问
这个在哪里改

**Comment by JinlingLiCode** [comment]
> on_fitepoch_end() 缺少 1 个位置参数：'fi' 正常显示可以进行训练训练，请问 这个在哪里改

我跟你出现的情况一样，你找到原因了吗

**Comment by Master-tian** [comment]
> > on_fitepoch_end() 训练可以进行 1 个位置的训练显示参数：'fi' 正常，这个人在哪里改
> 
> 我跟你出现的情况一样，你找到原因了

把其中一行注释掉好像就没事了，该问题解决了

**Comment by zxsitu** [comment]
@msddmzy @Master-tian 大佬们您好，好像我遇到的问题跟你们相似，请问你们是如何解决这个问题的呢？
将哪一行注释掉呢？

```
Traceback (most recent call last):
  File "train_sparsity.py", line 674, in <module>
    main(opt)
  File "train_sparsity.py", line 571, in main
    train(opt.hyp, opt, device, callbacks)
  File "train_sparsity.py", line 419, in train
    callbacks.run('on_fit_epoch_end', log_vals, bn_weights.numpy() ,epoch, best_fitness, fi)
  File "F:\PycharmProjects\pythonProject4\yolov5prune-6.0\utils\callbacks.py", line 77, in run
    logger['callback'](*args, **kwargs)
TypeError: on_fit_epoch_end() takes 5 positional arguments but 6 were given
```

**Comment by Master-tian** [comment]
您好，您的打包文件已收到！                                     ——田志平

**Comment by Master-tian** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        搞错了，不是注释。对比yolov5官方的文件，补齐utills文件夹下loggers文件下的文件，在训练的时候调整下导包的路径即可
            
        
    
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    在2022年6月3日 ***@***.***> 写道： 




@msddmzy @Master-tian 大佬们您好，好像我遇到的问题跟你们相似，请问你们是如何解决这个问题的呢？

将哪一行注释掉呢？

Traceback (most recent call last):

  File "train_sparsity.py", line 674, in <module>

    main(opt)

  File "train_sparsity.py", line 571, in main

    train(opt.hyp, opt, device, callbacks)

  File "train_sparsity.py", line 419, in train

    callbacks.run('on_fit_epoch_end', log_vals, bn_weights.numpy() ,epoch, best_fitness, fi)

  File "F:\PycharmProjects\pythonProject4\yolov5prune-6.0\utils\callbacks.py", line 77, in run

    logger['callback'](*args, **kwargs)

TypeError: on_fit_epoch_end() takes 5 positional arguments but 6 were given

**Comment by River-Cold** [comment]
> @msddmzy @Master-tian 大佬们您好，好像我遇到的问题跟你们相似，请问你们是如何解决这个问题的呢？ 将哪一行注释掉呢？
> 
> ```
> Traceback (most recent call last):
>   File "train_sparsity.py", line 674, in <module>
>     main(opt)
>   File "train_sparsity.py", line 571, in main
>     train(opt.hyp, opt, device, callbacks)
>   File "train_sparsity.py", line 419, in train
>     callbacks.run('on_fit_epoch_end', log_vals, bn_weights.numpy() ,epoch, best_fitness, fi)
>   File "F:\PycharmProjects\pythonProject4\yolov5prune-6.0\utils\callbacks.py", line 77, in run
>     logger['callback'](*args, **kwargs)
> TypeError: on_fit_epoch_end() takes 5 positional arguments but 6 were given
> ```

@zxsitu 我的普通训练可以正常进行，稀疏训练时遇到了一样的问题，请问您解决了吗？

**Comment by Master-tian** [comment]
您好，您的打包文件已收到！                                     ——田志平

**Comment by Chan-rx** [comment]
> > @msddmzy @Master-tian 大佬们您好，好像我遇到的问题跟你们相似，请问你们是如何解决这个问题的呢？ 将哪一行注释掉呢？
> > ```
> > Traceback (most recent call last):
> >   File "train_sparsity.py", line 674, in <module>
> >     main(opt)
> >   File "train_sparsity.py", line 571, in main
> >     train(opt.hyp, opt, device, callbacks)
> >   File "train_sparsity.py", line 419, in train
> >     callbacks.run('on_fit_epoch_end', log_vals, bn_weights.numpy() ,epoch, best_fitness, fi)
> >   File "F:\PycharmProjects\pythonProject4\yolov5prune-6.0\utils\callbacks.py", line 77, in run
> >     logger['callback'](*args, **kwargs)
> > TypeError: on_fit_epoch_end() takes 5 positional arguments but 6 were given
> > ```
> 
> @zxsitu 我的普通训练可以正常进行，稀疏训练时遇到了一样的问题，请问您解决了吗？

我也遇到了同样问题， 请问您解决了吗

**Comment by Master-tian** [comment]
您好，您的打包文件已收到！                                     ——田志平

**Comment by fangxuehouwuming** [comment]
没解决啊

**Comment by Master-tian** [comment]
您好，您的打包文件已收到！                                     ——田志平

**Comment by fangxuehouwuming** [comment]
6.0版本稀疏训练train_sparity.py报错TypeError: on_fit_epoch_end() takes 5 positional arguments but 6 were given

**Comment by fangxuehouwuming** [comment]
@zxsitu 你好，6.0版本稀疏训练train_sparity.py报错TypeError: on_fit_epoch_end() takes 5 positional arguments but 6 were given，这个问题你解决了吗

**Comment by fangxuehouwuming** [comment]
@503092317 

> > > on_fitepoch_end() 训练可以进行 1 个位置的训练显示参数：'fi' 正常，这个人在哪里改
> > 
> > 
> > 我跟你出现的情况一样，你找到原因了
> 
> 把其中一行注释掉好像就没事了，该问题解决了

6.0版本稀疏训练train_sparity.py报错TypeError: on_fit_epoch_end() takes 5 positional arguments but 6 were given，你好，这个问题解决了吗

**Comment by Kay545** [comment]
@fangxuehouwuming  去掉一个参数（bn_weights.numpy()），并且不要保存csv就行了，😂

**Comment by Master-tian** [comment]
您好，您的打包文件已收到！                                     ——田志平
