### ISSUE TITLE
Got 'ModelPruned' object has no attribute 'nc' error when export model to onnx

### ISSUE THREAD

**Issue by szwyx999** [midasklr/yolov5prune#76]
作者你好， 
  非常感谢你的工作！我下载了你的6.0分支并按照你的说明进行了稀疏训练和剪枝，但得到的结果我通过export时，出现上述错误，但如果对原模型导出时没问题的，请问这是什么原因？
  另外，您所说的不断迭代是什么意思？是不是我先基于原始的模型->稀疏训练->剪枝->稀疏训练->剪枝。。。?
  谢谢！

  以下是我的错误记录，

 (yolo5) PS D:\pythonwork\yolo5\yolov5prune-6.0> python.exe .\export.py --weight .\pruned_model.pt --data .\data\J7.yaml --device 0
export: data=.\data\J7.yaml, weights=['.\\pruned_model.pt'], imgsz=[640, 640], batch_size=1, device=0, half=False, inplace=False, train=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=12, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['torchscript', 'onnx']
YOLOv5  2022-1-5 torch 1.10.2 CUDA:0 (NVIDIA GeForce GTX 1650 SUPER, 4096MiB)

Traceback (most recent call last):
  File ".\export.py", line 464, in <module>
    main(opt)
  File ".\export.py", line 459, in main
    run(**vars(opt))
  File "C:\Users\87033\.conda\envs\yolo5\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File ".\export.py", line 370, in run
    nc, names = model.nc, model.names  # number of classes, class names
  File "C:\Users\87033\.conda\envs\yolo5\lib\site-packages\torch\nn\modules\module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'ModelPruned' object has no attribute 'nc'
(yolo5) PS D:\pythonwork\yolo5\yolov5prune-6.0>

**Comment by szwyx999** [comment]
好像是后面再要经过微调后才能转换。
python finetune.py ...
但，经过这个操作以后，我获得的模型比原来大了一倍。
也就是说，正常训练的模型14MB，经过稀疏训练，剪枝后 得到的模型为20MB左右，然后再经过微调，模型变成40MB。即使按照作者所说的，原来yolo5的模型是半精度保存的，经过剪枝调整后也大了一倍，这是为何？

**Comment by szwyx999** [comment]
好像是后面再要经过微调后才能转换。
python finetune.py ...
但，经过这个操作以后，我获得的模型比原来大了一倍。
也就是说，正常训练的模型14MB，经过稀疏训练，剪枝后 得到的模型为20MB左右，然后再经过微调，模型变成40MB。即使按照作者所说的，原来yolo5的模型是半精度保存的，经过剪枝调整后也大了一倍，这是为何？
