### ISSUE TITLE
pruned.py报错

### ISSUE THREAD

**Issue by HU-jin1620** [midasklr/yolov5prune#81]
Fusing layers... 
Model Summary: 224 layers, 7059304 parameters, 0 gradients, 16.3 GFLOPs
Traceback (most recent call last):
  File "F:/yolov5-master-bing/prune.py", line 794, in <module>
    test_prune(opt.data,
  File "F:/yolov5-master-bing/prune.py", line 376, in test_prune
    highest_thre = min(highest_thre)
ValueError: min() arg is an empty sequence
highest_thre: []

Process finished with exit code 1

**Comment by CVUsers** [comment]
Have you solved it? I also encountered this problem

**Comment by HU-jin1620** [comment]
yes, you can try to delete the .cache quotation from the dataset. I solved it by this way.




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月5日(周四) 中午11:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [midasklr/yolov5prune] pruned.py报错 (Issue #81)




 
Have you solved it? I also encountered this problem

**Comment by Dimitri666** [comment]
我尝试了这种方法，
没有效果
