### ISSUE TITLE
遇到一个问题,麻烦博主看一下

### ISSUE THREAD

**Issue by kenan666** [midasklr/yolov5prune#83]
Traceback (most recent call last):                                                                                                               
     File "train_sparsity.py", line 633, in <module>                                                                                                   
          train(hyp, opt, device, tb_writer)                                                                                                            
     File "train_sparsity.py", line 381, in train                                                                                                      
          mloss = (mloss * i + loss_items) / (i + 1)  # update mean losses                                                                            
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0 

#以上这个问题怎么看？

**Comment by NefarianZ** [comment]
你好 这个问题解决了吗？我也遇到这个问题了。

**Comment by Zhengzhiyang0000** [comment]
你好这个问题解决了吗

**Comment by wei3044** [comment]
同问 解决了吗
