### ISSUE TITLE
6.0版本稀疏训练train_sparity.py报错TypeError: on_fit_epoch_end() takes 5 positional arguments but 6 were given

### ISSUE THREAD

**Issue by zxsitu** [midasklr/yolov5prune#95]
6.0版本，稀疏训练，运行train_sparity.py时报错
```
Traceback (most recent call last):
  File "train_sparsity.py", line 674, in <module>
    main(opt)
  File "train_sparsity.py", line 571, in main
    train(opt.hyp, opt, device, callbacks)
  File "train_sparsity.py", line 419, in train
    callbacks.run('on_fit_epoch_end', log_vals, bn_weights.numpy() ,epoch, best_fitness, fi)
  File "F:\PycharmProjects\pythonProject4\yolov5prune-6.0\utils\callbacks.py", line 77, in run
    logger['callback'](*args, **kwargs)
TypeError: on_fit_epoch_end() takes 5 positional arguments but 6 were given
```

**Comment by WANGCHAO1996** [comment]
请问怎么解决的

**Comment by mumu171019** [comment]
请问解决了吗  我也遇到了同样的问题

**Comment by fangxuehouwuming** [comment]
@WANGCHAO1996 请问解决了吗

**Comment by fangxuehouwuming** [comment]
@zxsitu 请问解决了吗

**Comment by fangxuehouwuming** [comment]
@mumu171019 请问解决了吗

**Comment by fangxuehouwuming** [comment]
@midasklr 请问解决了吗
