### ISSUE TITLE
关于训练报错的问题 TypeError: on_fit_epoch_end() missing 1 required positional argument: 'fi'

### ISSUE THREAD

**Issue by ASguoyue** [midasklr/yolov5prune#96]
Traceback (most recent call last):
  File "/home/aCode/yolov5prune-6.0/train.py", line 626, in <module>
    main(opt)
  File "/home/a/Code/yolov5prune-6.0/train.py", line 523, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/a/Code/yolov5prune-6.0/train.py", line 374, in train
    callbacks.run('on_fit_epoch_end', log_vals, epoch, best_fitness, fi)
  File "/home/a/Code/yolov5prune-6.0/utils/callbacks.py", line 77, in run
    logger['callback'](*args, **kwargs)
TypeError: on_fit_epoch_end() missing 1 required positional argument: 'fi'

**Comment by ASguoyue** [comment]
请问各位大佬门遇到了吗 求解答

**Comment by ASguoyue** [comment]
以解决

**Comment by Du-yaowen** [comment]
你好，请问怎么解决的呀？

**Comment by xiaomujiang** [comment]
> 以解决

请问，怎么解决的

**Comment by Wisdom2wisdom** [comment]
怎么解决啊，谢谢

**Comment by fangxuehouwuming** [comment]
同问怎么解决

**Comment by fangxuehouwuming** [comment]
@ASguoyue 请问你是怎么解决的

**Comment by fangxuehouwuming** [comment]
@Wisdom2wisdom 你好，请问解决了吗

**Comment by fangxuehouwuming** [comment]
@xiaomujiang 你好，请问解决了吗
