### ISSUE TITLE
剪枝  python prune.py --percent 0.5 --weights runs/train/exp2/weights/last.pt --data data/voc.yaml --cfg models/yolov5s.yaml出现错误：TypeError: run() got an unexpected keyword argument 'cfg'

### ISSUE THREAD

**Issue by YTTT9** [midasklr/yolov5prune#97]
(yolov5) D:\AAAAAAAAA\YOLOV5-4.0\QQQQ\7Q-yolov5prune-6.0>python prune.py --percent 0.5 --weights weight/last.pt --data data/coco128.yaml
yolo: data=data/coco128.yaml, weights=['weight/last.pt'], cfg=D:\AAAAAAAAA\YOLOV5-4.0\QQQQ\7Q-yolov5prune-6.0\models\yolov5s.yaml, percent=0.5, batch_size=8, imgsz=416, conf_thres=0.001, iou_thres=0.6, task=v
al, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=D:\AAAAAAAAA\YOLOV5-4.0\QQQQ\7Q-yolov5prune-6.0\runs\val, n
ame=exp, exist_ok=False, half=False, dnn=False
test before prune ...
Traceback (most recent call last):
  File "prune.py", line 805, in <module>
    main(opt)
  File "prune.py", line 775, in main
    run(**vars(opt))
  File "D:\anaconda\envs\yolov5\lib\site-packages\torch\autograd\grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
TypeError: run() got an unexpected keyword argument 'cfg'

**Comment by cxy-ccc** [comment]
请问解决了吗

**Comment by wynshiter** [comment]
在 prune.py 的run 函数中把cfg 参数加上, 下面两个的opt 其实要统一的
```python
if opt.task in ('train', 'val', 'test'):  # run normally
        if opt.conf_thres > 0.001:  # https://github.com/ultralytics/yolov5/issues/1466
            LOGGER.info(f'WARNING: confidence threshold {opt.conf_thres} >> 0.001 will produce invalid mAP values.')
        LOGGER.info(f'test before prune ... ')
        run(**vars(opt))
        LOGGER.info('='*100)
        LOGGER.info('Test after prune ... ')
        run_prune(**vars(opt))
```

**Comment by Anyzhuguai** [comment]
```
def run(data,
        weights=None,  # model.pt path(s)
        percent=0,
        batch_size=32,  # batch size
        imgsz=640,  # inference size (pixels)
        conf_thres=0.001,  # confidence threshold
        iou_thres=0.6,  # NMS IoU threshold
        task='val',  # train, val, test, speed or study
        device='',  # cuda device, i.e. 0 or 0,1,2,3 or cpu
        workers=8,  # max dataloader workers (per RANK in DDP mode)
        single_cls=False,  # treat as single-class dataset
        augment=False,  # augmented inference
        verbose=False,  # verbose output
        save_txt=False,  # save results to *.txt
        save_hybrid=False,  # save label+prediction hybrid results to *.txt
        save_conf=False,  # save confidences in --save-txt labels
        save_json=False,  # save a COCO-JSON results file
        project=ROOT / 'runs/val',  # save to project/name
        name='exp',  # save to project/name
        exist_ok=False,  # existing project/name ok, do not increment
        half=True,  # use FP16 half-precision inference
        dnn=False,  # use OpenCV DNN for ONNX inference
        model=None,
        dataloader=None,
        save_dir=Path(''),
        plots=True,
        callbacks=Callbacks(),
        compute_loss=None,
        cfg='models/yolov5s.pt' `#加上一个cfg参数应该可以解决
        ):
```
run函数缺少cfg参数的声明，应该添加上
